//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteInterface.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string _return {
            get {
                return ResourceManager.GetString("return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actif.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface Distante.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string boxDetailTitle {
            get {
                return ResourceManager.GetString("boxDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution.
        /// </summary>
        public static string boxExecutionTitle {
            get {
                return ResourceManager.GetString("boxExecutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Journal.
        /// </summary>
        public static string boxLogTitle {
            get {
                return ResourceManager.GetString("boxLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel métier.
        /// </summary>
        public static string businessSoftware {
            get {
                return ResourceManager.GetString("businessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer ou modifier un travail de sauvegarde.
        /// </summary>
        public static string createJobViewTitle {
            get {
                return ResourceManager.GetString("createJobViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire de destination :.
        /// </summary>
        public static string destinationDirectory {
            get {
                return ResourceManager.GetString("destinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire de destination doit être différent du répertoire source..
        /// </summary>
        public static string destinationPathEqualsSourcePath {
            get {
                return ResourceManager.GetString("destinationPathEqualsSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle.
        /// </summary>
        public static string differential {
            get {
                return ResourceManager.GetString("differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire de destination est obligatoire..
        /// </summary>
        public static string emptyDestinationDirectoryError {
            get {
                return ResourceManager.GetString("emptyDestinationDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le label est obligatoire.
        /// </summary>
        public static string emptyLabelError {
            get {
                return ResourceManager.GetString("emptyLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source est obligatoire..
        /// </summary>
        public static string emptySourceDirectoryError {
            get {
                return ResourceManager.GetString("emptySourceDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de la liste des extensions n&apos;est pas respectée. Merci d&apos;utiliser ce format : .png;.pdf;.xlsx.
        /// </summary>
        public static string extensionFormatError {
            get {
                return ResourceManager.GetString("extensionFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de fichiers restants.
        /// </summary>
        public static string filesLeftToCopy {
            get {
                return ResourceManager.GetString("filesLeftToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux de sauvegarde.
        /// </summary>
        public static string jobBackupList {
            get {
                return ResourceManager.GetString("jobBackupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde.
        /// </summary>
        public static string jobCreateBackupType {
            get {
                return ResourceManager.GetString("jobCreateBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire de destination *.
        /// </summary>
        public static string jobCreateDestinationDirectory {
            get {
                return ResourceManager.GetString("jobCreateDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire source *.
        /// </summary>
        public static string jobCreateSourceDirectory {
            get {
                return ResourceManager.GetString("jobCreateSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde :.
        /// </summary>
        public static string jobType {
            get {
                return ResourceManager.GetString("jobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label *.
        /// </summary>
        public static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue (effectif après un redémarrage).
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mo.
        /// </summary>
        public static string megabyteUnit {
            get {
                return ResourceManager.GetString("megabyteUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface à Distance.
        /// </summary>
        public static string remoteInterface {
            get {
                return ResourceManager.GetString("remoteInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une instance d&apos;EasySave est déjà en cours d&apos;exécution....
        /// </summary>
        public static string singleInstance {
            get {
                return ResourceManager.GetString("singleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire source :.
        /// </summary>
        public static string sourceDirectory {
            get {
                return ResourceManager.GetString("sourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source n&apos;existe pas..
        /// </summary>
        public static string sourceDirectoryNotExistsError {
            get {
                return ResourceManager.GetString("sourceDirectoryNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Totale.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille total des fichiers :.
        /// </summary>
        public static string totalFilesSize {
            get {
                return ResourceManager.GetString("totalFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre total de fichiers à copier.
        /// </summary>
        public static string totalFilesToCopy {
            get {
                return ResourceManager.GetString("totalFilesToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille restante.
        /// </summary>
        public static string totalSizeRemaining {
            get {
                return ResourceManager.GetString("totalSizeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
    }
}
